### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by bruciebruce** [KimMeen/Time-LLM#10]
I am running this on google colab with a T4 GPU.  

Any idea why the gpu is not being recognized?  I do not see any assignments anywhere.

------------------------------------------- start of log -------------------------------------------------------

+ model_name=TimeLLM
+ train_epochs=100
+ learning_rate=0.01
+ llama_layers=32
+ master_port=00097
+ num_process=8
+ batch_size=24
+ d_model=32
+ d_ff=128
+ comment=TimeLLM-ETTh1
+ accelerate launch --multi_gpu --mixed_precision bf16 --num_processes 8 --main_process_port 00097 run_main.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/ETT-small/ --data_path ETTh1.csv --model_id ETTh1_512_96 --model TimeLLM --data ETTh1 --features M --seq_len 512 --label_len 48 --pred_len 96 --factor 3 --enc_in 7 --dec_in 7 --c_out 7 --des Exp --itr 1 --d_model 32 --d_ff 128 --batch_size 24 --learning_rate 0.01 --llm_layers 32 --train_epochs 100 --model_comment TimeLLM-ETTh1
[2024-02-22 16:17:36,426] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_machines` was set to a value of `1`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2024-02-22 16:17:55,327] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-22 16:17:55,384] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-22 16:17:55,515] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-22 16:17:55,601] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-22 16:17:55,634] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-22 16:17:55,638] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-22 16:17:55,751] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-22 16:17:55,774] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-22 16:18:23,485] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-02-22 16:18:23,491] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-02-22 16:18:23,495] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-02-22 16:18:23,502] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-02-22 16:18:23,507] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-02-22 16:18:23,507] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2024-02-22 16:18:23,510] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-02-22 16:18:23,512] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-02-22 16:18:23,513] [INFO] [comm.py:637:init_distributed] cdb=None
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab_Notebooks/Time-LLM/run_main.py", line 104, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab_Notebooks/Time-LLM/run_main.py", line 104, in <module>
  File "/content/drive/MyDrive/Colab_Notebooks/Time-LLM/run_main.py", line 104, in <module>
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab_Notebooks/Time-LLM/run_main.py", line 104, in <module>
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab_Notebooks/Time-LLM/run_main.py", line 126, in <module>
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab_Notebooks/Time-LLM/run_main.py", line 104, in <module>
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab_Notebooks/Time-LLM/run_main.py", line 104, in <module>
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab_Notebooks/Time-LLM/run_main.py", line 104, in <module>
    accelerator = Accelerator(kwargs_handlers=[ddp_kwargs], deepspeed_plugin=deepspeed_plugin)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/accelerator.py", line 345, in __init__
    self.state = AcceleratorState(
  File "/usr/local/lib/python3.9/dist-packages/accelerate/state.py", line 680, in __init__
    PartialState(cpu, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/state.py", line 182, in __init__
    torch.cuda.set_device(self.device)
  File "/usr/local/lib/python3.9/dist-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
**RuntimeError: CUDA error: invalid device ordinal**
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    accelerator = Accelerator(kwargs_handlers=[ddp_kwargs], deepspeed_plugin=deepspeed_plugin)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/accelerator.py", line 345, in __init__
    self.state = AcceleratorState(
  File "/usr/local/lib/python3.9/dist-packages/accelerate/state.py", line 680, in __init__
    PartialState(cpu, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/state.py", line 182, in __init__
    torch.cuda.set_device(self.device)
  File "/usr/local/lib/python3.9/dist-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

------------------------------------------- end of log  --------------------------------------------------------

**Comment by bruciebruce** [comment]
This is related to the fact that I have only 1 gpu.

**Comment by bruciebruce** [comment]
In the shell scripts I set **num_process=1** and dropped the following: **--multi_gpu --mixed_precision bf16**
