### ISSUE TITLE
Run run_main.py in WSL Ubuntu Failed

### ISSUE THREAD

**Issue by summerlovewarum** [KimMeen/Time-LLM#153]
Try to run run_main.py in WSL, but it failed. the Traceback is as below:

(rungpt2) summer_82asd@DESKTOP-7U5KO5T:/mnt/d/download/time-llm-main$ python3 run_main.py
Traceback (most recent call last):
  File "/mnt/d/download/time-llm-main/run_main.py", line 11, in <module>
    from data_provider.data_factory import data_provider
  File "/mnt/d/download/time-llm-main/data_provider/data_factory.py", line 1, in <module>
    from data_provider.data_loader import Dataset_ETT_hour, Dataset_ETT_minute, Dataset_Custom, Dataset_M4
  File "/mnt/d/download/time-llm-main/data_provider/data_loader.py", line 3, in <module>
    import pandas as pd
  File "/mnt/d/download/Time-LLM-main/rungpt2/lib/python3.11/site-packages/pandas/__init__.py", line 48, in <module>
    from pandas.core.api import (
  File "/mnt/d/download/Time-LLM-main/rungpt2/lib/python3.11/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/mnt/d/download/Time-LLM-main/rungpt2/lib/python3.11/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/mnt/d/download/Time-LLM-main/rungpt2/lib/python3.11/site-packages/pandas/core/groupby/generic.py", line 76, in <module>
    from pandas.core.frame import DataFrame
  File "/mnt/d/download/Time-LLM-main/rungpt2/lib/python3.11/site-packages/pandas/core/frame.py", line 172, in <module>
    from pandas.core.generic import NDFrame
  File "/mnt/d/download/Time-LLM-main/rungpt2/lib/python3.11/site-packages/pandas/core/generic.py", line 147, in <module>
    from pandas.core.describe import describe_ndframe
  File "/mnt/d/download/Time-LLM-main/rungpt2/lib/python3.11/site-packages/pandas/core/describe.py", line 45, in <module>
    from pandas.io.formats.format import format_percentiles
  File "/mnt/d/download/Time-LLM-main/rungpt2/lib/python3.11/site-packages/pandas/io/formats/format.py", line 105, in <module>
    from pandas.io.common import (
  File "/mnt/d/download/Time-LLM-main/rungpt2/lib/python3.11/site-packages/pandas/io/common.py", line 8, in <module>
    import bz2
  File "/usr/local/python3.11/lib/python3.11/bz2.py", line 17, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

anyone knows how to fix it?

Thanks!

**Comment by Tom5246** [comment]
This seems to be a bug in WSL. You should try running it on a pure Linux system, such as a cloud server

**Comment by summerlovewarum** [comment]
By any chance to install some patch to fix this bug?

**Comment by Tom5246** [comment]
I tried running it on WSL, but it ultimately failed. Perhaps you could give it a try. I have not encountered this problem after switching to the Ubuntu server
