### ISSUE TITLE
Accelerate command not found

### ISSUE THREAD

**Issue by NimeeshaChan** [KimMeen/Time-LLM#20]
Hello, I am trying to run TimeLLM_ETTm2.sh, after just downloading the zip file, and am getting this error. 

./scripts/TimeLLM_ETTm2.sh: line 14: accelerate: command not found
./scripts/TimeLLM_ETTm2.sh: line 40: accelerate: command not found
./scripts/TimeLLM_ETTm2.sh: line 68: accelerate: command not found
./scripts/TimeLLM_ETTm2.sh: line 96: accelerate: command not found

When running pip list, accelerate shows up as installed. I also tried setting up the accelerate config. What should I do next?

Thank you!

**Comment by KimMeen** [comment]
Hi @NimeeshaChan, could you provide more detailed information? Also, please check your environment configuration, e.g. did you activate the correct environment and installed all dependencies successfully?

**Comment by NimeeshaChan** [comment]
Hi Kim, thank you for your prompt reply! I'm on a remote server, and have downloaded accelerate successfully.

Here's is the output from running pip list in the virtual environment.

Package                  Version
------------------------ -----------
accelerate               0.20.3
annotated-types          0.6.0
certifi                  2024.2.2
charset-normalizer       3.3.2
cmake                    3.28.3
contourpy                1.2.0
cycler                   0.12.1
deepspeed                0.13.0
einops                   0.7.0
filelock                 3.13.1
fonttools                4.49.0
fsspec                   2024.2.0
hjson                    3.1.0
huggingface-hub          0.21.3
idna                     3.6
Jinja2                   3.1.3
joblib                   1.3.2
kiwisolver               1.4.5
lit                      17.0.6
MarkupSafe               2.1.5
matplotlib               3.7.0
mpmath                   1.3.0
networkx                 3.2.1
ninja                    1.11.1.1
numpy                    1.23.5
nvidia-cublas-cu11       11.10.3.66
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu11        8.5.0.96
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu11        10.9.0.58
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu11       10.2.10.91
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu11     11.7.4.91
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu11         2.14.3
nvidia-nccl-cu12         2.19.3
nvidia-nvjitlink-cu12    12.3.101
nvidia-nvtx-cu11         11.7.91
nvidia-nvtx-cu12         12.1.105
packaging                23.2
pandas                   1.5.3
peft                     0.4.0
pillow                   10.2.0
pip                      23.1.2
psutil                   5.9.8
py-cpuinfo               9.0.0
pydantic                 2.6.3
pydantic_core            2.16.3
pynvml                   11.5.0
pyparsing                3.1.1
python-dateutil          2.9.0.post0
pytz                     2024.1
PyYAML                   6.0.1
regex                    2023.12.25
requests                 2.31.0
safetensors              0.4.2
scikit-learn             1.2.2
scipy                    1.12.0
setuptools               65.5.0
six                      1.16.0
sympy                    1.12
threadpoolctl            3.3.0
tokenizers               0.13.3
torch                    2.0.1
tqdm                     4.65.0
transformers             4.31.0
triton                   2.0.0
typing_extensions        4.10.0
urllib3                  2.2.1
wheel                    0.42.0

I was unable to pip install scipy==1.5.4 and it defaulted to 1.12.0 instead (was running into errors). Is that the reason?

**Comment by NimeeshaChan** [comment]
This is the version I'm on:

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

I set up a new environment, with Python 3.9, and was able to successfully install all the requirements (fixed the scipy issue). However, I am still getting the same result:

Command: sudo bash ./scripts/TimeLLM_ETTm2.sh 
[sudo] password for nimeesha: 

./scripts/TimeLLM_ETTm2.sh: line 14: accelerate: command not found
./scripts/TimeLLM_ETTm2.sh: line 40: accelerate: command not found
./scripts/TimeLLM_ETTm2.sh: line 68: accelerate: command not found
./scripts/TimeLLM_ETTm2.sh: line 96: accelerate: command not found

Please let me know what other information I can provide! Thank you.

**Comment by NimeeshaChan** [comment]
Also, if I just run bash ./scripts/TimeLLM_ETTm2.sh 

[2024-03-03 22:28:27,590] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[W socket.cpp:426] [c10d] The server socket has failed to bind to [::]:97 (errno: 13 - Permission denied).
[W socket.cpp:426] [c10d] The server socket has failed to bind to 0.0.0.0:97 (errno: 13 - Permission denied).
[E socket.cpp:462] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "/home/nimeesha/.venvs/timellm3.9/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/accelerate/commands/launch.py", line 932, in launch_command
    multi_gpu_launcher(args)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/accelerate/commands/launch.py", line 627, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 241, in launch_agent
    result = agent.run()
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 723, in run
    result = self._invoke_run(role)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 858, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 692, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 546, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:97 (errno: 13 - Permission denied). The server socket has failed to bind to 0.0.0.0:97 (errno: 13 - Permission denied).
[2024-03-03 22:28:29,369] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[W socket.cpp:426] [c10d] The server socket has failed to bind to [::]:97 (errno: 13 - Permission denied).
[W socket.cpp:426] [c10d] The server socket has failed to bind to 0.0.0.0:97 (errno: 13 - Permission denied).
[E socket.cpp:462] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "/home/nimeesha/.venvs/timellm3.9/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/accelerate/commands/launch.py", line 932, in launch_command
    multi_gpu_launcher(args)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/accelerate/commands/launch.py", line 627, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 241, in launch_agent
    result = agent.run()
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 723, in run
    result = self._invoke_run(role)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 858, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 692, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 546, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:97 (errno: 13 - Permission denied). The server socket has failed to bind to 0.0.0.0:97 (errno: 13 - Permission denied).
[2024-03-03 22:28:31,149] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[W socket.cpp:426] [c10d] The server socket has failed to bind to [::]:97 (errno: 13 - Permission denied).
[W socket.cpp:426] [c10d] The server socket has failed to bind to 0.0.0.0:97 (errno: 13 - Permission denied).
[E socket.cpp:462] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "/home/nimeesha/.venvs/timellm3.9/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/accelerate/commands/launch.py", line 932, in launch_command
    multi_gpu_launcher(args)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/accelerate/commands/launch.py", line 627, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 241, in launch_agent
    result = agent.run()
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 723, in run
    result = self._invoke_run(role)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 858, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 692, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 546, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:97 (errno: 13 - Permission denied). The server socket has failed to bind to 0.0.0.0:97 (errno: 13 - Permission denied).
[2024-03-03 22:28:32,937] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[W socket.cpp:426] [c10d] The server socket has failed to bind to [::]:97 (errno: 13 - Permission denied).
[W socket.cpp:426] [c10d] The server socket has failed to bind to 0.0.0.0:97 (errno: 13 - Permission denied).
[E socket.cpp:462] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "/home/nimeesha/.venvs/timellm3.9/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/accelerate/commands/launch.py", line 932, in launch_command
    multi_gpu_launcher(args)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/accelerate/commands/launch.py", line 627, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 241, in launch_agent
    result = agent.run()
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 723, in run
    result = self._invoke_run(role)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 858, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 692, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 546, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:97 (errno: 13 - Permission denied). The server socket has failed to bind to 0.0.0.0:97 (errno: 13 - Permission denied).

I thought running sudo would force the socket to connect, but perhaps that is causing the issue? How would I go about fixing this issue then?

**Comment by KimMeen** [comment]
This error typically occurs because the `accelerate` command is not installed in your environment or is not accessible in your system's PATH when using `sudo`. 

1. Make sure that the `accelerate` library is installed in your environment. This may answer why `bash ./scripts/TimeLLM_ETTm2.sh` and `sudo bash ./scripts/TimeLLM_ETTm2.sh` give you different results. When you use `sudo`, the environment variables (including PATH) might be different from your user's environment.
2. Try other available ports larger than 1024 by setting `master_port` in the running scripts. If possible, try to avoid running the scripts as root.

Overall, this is a general configuration issue, and these resources may be helpful: (1) https://discuss.huggingface.co/t/accelerate-command-not-found/20163 (2) https://huggingface.co/docs/accelerate/en/basic_tutorials/install (3) https://stackoverflow.com/questions/24001147/python-bind-socket-error-errno-13-permission-denied

**Comment by NimeeshaChan** [comment]
Thank you very much! I think that fixed it, but I'm now running into another error when running the same bash ./scripts/TimeLLM_ETTm2.sh

[2024-03-04 11:56:15,802] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-03-04 11:56:17,405] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [01:54<00:00, 57.02s/it]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/mnt/aamv_data/nimeesha_workspace/nimeesha_workspace/first_paper/Time-LLM-main/run_main.py", line 208, in <module>
    outputs = model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/aamv_data/nimeesha_workspace/nimeesha_workspace/first_paper/Time-LLM-main/models/TimeLLM.py", line 103, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
  File "/mnt/aamv_data/nimeesha_workspace/nimeesha_workspace/first_paper/Time-LLM-main/models/TimeLLM.py", line 144, in forecast
    source_embeddings = self.mapping_layer(self.word_embeddings.permute(1, 0)).permute(1, 0)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
Traceback (most recent call last):
  File "/home/nimeesha/.venvs/timellm3.9/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/accelerate/commands/launch.py", line 941, in launch_command
    simple_launcher(args)
  File "/home/nimeesha/.venvs/timellm3.9/lib/python3.9/site-packages/accelerate/commands/launch.py", line 603, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/nimeesha/.venvs/timellm3.9/bin/python3.9', 'run_main.py', '--task_name', 'long_term_forecast', '--is_training', '1', '--root_path', './dataset/ETT-small/', '--data_path', 'ETTm2.csv', '--model_id', 'ETTm2_512_96', '--model', 'TimeLLM', '--data', 'ETTm2', '--features', 'M', '--seq_len', '512', '--label_len', '48', '--pred_len', '96', '--factor', '3', '--enc_in', '7', '--dec_in', '7', '--c_out', '7', '--des', 'Exp', '--itr', '1', '--d_model', '32', '--d_ff', '128', '--batch_size', '16', '--learning_rate', '0.01', '--llm_layers', '32', '--train_epochs', '10', '--model_comment', 'TimeLLM-ETTm2']' returned non-zero exit status 1.

Should I be changing part of the code?

**Comment by HamBa-m** [comment]
@NimeeshaChan you should open a new issue concerning this problem and close this one. I think it is related to a missing line somewhere in the code to transfer all data to the GPU.

**Comment by JHM69** [comment]
Facing Same Error:

```
$ sudo bash ./scripts/TimeLLM_ETTm2.sh
./scripts/TimeLLM_ETTm2.sh: line 14: accelerate: command not found
./scripts/TimeLLM_ETTm2.sh: line 40: accelerate: command not found
./scripts/TimeLLM_ETTm2.sh: line 68: accelerate: command not found
./scripts/TimeLLM_ETTm2.sh: line 96: accelerate: command not found
```
