### ISSUE TITLE
CalledProcessError when running TimeLLM_ETTh1.sh

### ISSUE THREAD

**Issue by JerayuT** [KimMeen/Time-LLM#53]
When I run bash ./scripts/TimeLLM_ETTh1.sh, I get the following error:

`[2024-03-28 15:11:33,415] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.13/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/accelerate/commands/launch.py", line 941, in launch_command
    simple_launcher(args)
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/accelerate/commands/launch.py", line 603, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/.pyenv/versions/3.9.13/bin/python3.9', 'run_main.py', '--task_name', 'long_term_forecast', '--is_training', '1', '--root_path', './dataset/ETT-small/', '--data_path', 'ETTh1.csv', '--model_id', 'ETTh1_512_96', '--model', 'TimeLLM', '--data', 'ETTh1', '--features', 'M', '--seq_len', '512', '--label_len', '48', '--pred_len', '96', '--factor', '3', '--enc_in', '7', '--dec_in', '7', '--c_out', '7', '--des', 'Exp', '--itr', '1', '--d_model', '32', '--d_ff', '128', '--batch_size', '1', '--learning_rate', '0.01', '--llm_layers', '32', '--train_epochs', '1', '--model_comment', 'TimeLLM-ETTh1']' died with <Signals.SIGKILL: 9>.`

I'm currently running on a single GPU NVIDA GeForce RTX 3050Ti, CUDA: Build cuda_11.5.r11.5/compiler.30672275_0.

I've also adjusted the code to match the single GPU example provided in a previous issue: [#28 ](#28) and also set CUDA_HOME and CUDA_PATH to the nvcc dir, but I still receive the above error.

**Comment by stupidoge** [comment]
I think I have similar issue with 4090.

`(timellm) kaizhao@yons-MS-7E06:~/Downloads/Time-LLM-main$ bash ./scripts/TimeLLM_ETTh1.sh 
[2024-03-29 15:04:41,484] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2024-03-29 15:04:43,095] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/kaizhao/Downloads/Time-LLM-main/run_main.py", line 104, in <module>
    accelerator = Accelerator(kwargs_handlers=[ddp_kwargs], deepspeed_plugin=deepspeed_plugin)
  File "/home/kaizhao/anaconda3/envs/timellm/lib/python3.9/site-packages/accelerate/accelerator.py", line 282, in __init__
    deepspeed_plugin.set_mixed_precision(mixed_precision)
  File "/home/kaizhao/anaconda3/envs/timellm/lib/python3.9/site-packages/accelerate/utils/dataclasses.py", line 652, in set_mixed_precision
    raise ValueError(
ValueError: `--mixed_precision` arg cannot be set to `fp16` when `bf16` is set in the DeepSpeed config file.
Traceback (most recent call last):
  File "/home/kaizhao/anaconda3/envs/timellm/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/kaizhao/anaconda3/envs/timellm/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/kaizhao/anaconda3/envs/timellm/lib/python3.9/site-packages/accelerate/commands/launch.py", line 941, in launch_command
    simple_launcher(args)
  File "/home/kaizhao/anaconda3/envs/timellm/lib/python3.9/site-packages/accelerate/commands/launch.py", line 603, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/kaizhao/anaconda3/envs/timellm/bin/python', 'run_main.py', '--task_name', 'long_term_forecast', '--is_training', '1', '--root_path', './dataset/ETT-small/', '--data_path', 'ETTh1.csv', '--model_id', 'ETTh1_512_96', '--model', 'TimeLLM', '--data', 'ETTh1', '--features', 'M', '--seq_len', '512', '--label_len', '48', '--pred_len', '96', '--factor', '3', '--enc_in', '7', '--dec_in', '7', '--c_out', '7', '--des', 'Exp', '--itr', '1', '--d_model', '32', '--d_ff', '128', '--batch_size', '24', '--learning_rate', '0.01', '--llm_layers', '32', '--train_epochs', '100', '--model_comment', 'TimeLLM-ETTh1']' returned non-zero exit status 1.`

**Comment by JerayuT** [comment]
@stupidoge Were you able to resolve it?

**Comment by JerayuT** [comment]
This issue was resolved by using the GPT2 model instead of the LLAMA model.

In line 80 and 81 of run_main.py, changing the model allowed me to run the experiment with no errors on a single GPU.
`parser.add_argument('--llm_model', type=str, default='GPT2', help='LLM model') # LLAMA, GPT2, BERT
parser.add_argument('--llm_dim', type=int, default='768', help='LLM model dimension')# LLama7b:4096; GPT2-small:768; BERT-base:768
`

**Comment by JerayuT** [comment]
This issue was resolved by using the GPT2 model instead of the LLAMA model.

In line 80 and 81 of run_main.py, changing the model allowed me to run the experiment with no errors on a single GPU.
`parser.add_argument('--llm_model', type=str, default='GPT2', help='LLM model') # LLAMA, GPT2, BERT
parser.add_argument('--llm_dim', type=int, default='768', help='LLM model dimension')# LLama7b:4096; GPT2-small:768; BERT-base:768
`
