### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte

### ISSUE THREAD

**Issue by bruciebruce** [KimMeen/Time-LLM#8]
I am trying to run **bash ./scripts/TimeLLM_ETTh1.sh** up on google colab.  The only modification I made was to use
deepspeed==0.12.0 (and not deepspeed==0.13.0) that you have in your requirements.txt file.

**!bash -x ./scripts/TimeLLM_ETTh1.sh**
+ model_name=TimeLLM
+ train_epochs=100
+ learning_rate=0.01
+ llama_layers=32
+ master_port=00097
+ num_process=8
+ batch_size=24
+ d_model=32
+ d_ff=128
+ comment=TimeLLM-ETTh1
+ accelerate launch --multi_gpu --mixed_precision bf16 --num_processes 8 --main_process_port 00097 run_main.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/ETT-small/ --data_path ETTh1.csv --model_id ETTh1_512_96 --model TimeLLM --data ETTh1 --features M --seq_len 512 --label_len 48 --pred_len 96 --factor 3 --enc_in 7 --dec_in 7 --c_out 7 --des Exp --itr 1 --d_model 32 --d_ff 128 --batch_size 24 --learning_rate 0.01 --llm_layers 32 --train_epochs 100 --model_comment TimeLLM-ETTh1
[2024-02-20 23:12:01,131] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_machines` was set to a value of `1`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2024-02-20 23:12:29,074] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-20 23:12:29,090] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-20 23:12:29,127] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-20 23:12:29,251] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-20 23:12:29,312] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-20 23:12:29,322] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-20 23:12:29,343] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-20 23:12:29,567] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/accelerate/utils/deepspeed.py", line 52, in __init__
    config_decoded = base64.urlsafe_b64decode(config_file_or_dict).decode("utf-8")Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/accelerate/utils/deepspeed.py", line 52, in __init__
    config_decoded = base64.urlsafe_b64decode(config_file_or_dict).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab_Notebooks/Time-LLM/run_main.py", line 100, in <module>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/accelerate/utils/deepspeed.py", line 52, in __init__
    config_decoded = base64.urlsafe_b64decode(config_file_or_dict).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

[bash-TimeLLM_ETTh1.sh.txt](https://github.com/KimMeen/Time-LLM/files/14352200/bash-TimeLLM_ETTh1.sh.txt)

**Comment by bruciebruce** [comment]
Here is line # 100 of run_main.py (as referenced above):

 98 ->   args = parser.parse_args()
 99 ->   ddp_kwargs = DistributedDataParallelKwargs(find_unused_parameters=True)
100 -> **deepspeed_plugin = DeepSpeedPlugin(hf_ds_config='./ds_config_zero2.json')**
101 -> accelerator = Accelerator(kwargs_handlers=[ddp_kwargs], deepspeed_plugin=deepspeed_plugin)

**Comment by bruciebruce** [comment]
I forgot to upload this .json file.  It is there now.  Issue resolved.  Closing this.
